### ISSUE TITLE
The homepage is down

### ISSUE THREAD

**Issue by tom111** [johanlofberg/YALMIP#307]
It seems like somebody updated parts of the server software without checking compatibility of your homepage.  At the moment http://users.isy.liu.se/johanl/yalmip/ only returns many lines like this:

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /www/users/rt/johanl/yalmip/pmwiki.php on line 784

**Comment by johanlofberg** [comment]
Yep. Unfortunately on vacation so it will take a while to fix

Temporary work-around
https://groups.google.com/forum/?fromgroups#!topic/yalmip/nHYOsi_ajuw
