### ISSUE TITLE
Cplex warning

### ISSUE THREAD

**Issue by jonswarbrick** [johanlofberg/YALMIP#341]
Getting following warning when yalmip attempts to set the CPLEX options. Using CPLEX 12.6.1.

Warning: The function 'cplexlink1261' returned an mxArray with non-temporary scope. 
> In cplexoptimset/setCplexOptions
  In cplexoptimset/setCplexOptions
  In cplexoptimset
  In sdpsettings>setup_cplex_options (line 576)
  In sdpsettings (line 132)
  In yalmiptest (line 111)

**Comment by johanlofberg** [comment]
Bug in cplex in MATLAB2015b. Nothing we can do about it.

**Comment by tholden** [comment]
Despite the warnings, it does seem to pass YALMIP's tests using CPLEX and r2015b. So as a short term workaround:
    warning( 'off', 'MATLAB:lang:badlyScopedReturnValue' );
seems sensible.

@jonswarbrick this has been added to dynareOBC in commit: https://github.com/tholden/dynareOBC/commit/2d9b44dffec361caeef70f3c8425f30c4427a155
