### ISSUE TITLE
optimizer/subsref fails in R2013a

### ISSUE THREAD

**Issue by kvasnica** [johanlofberg/YALMIP#343]
R2013a, latest origin/develop (c00dbd4), works in R2014a, R2015b
```matlab
yalmip('clear');
A = sdpvar(2, 2, 'full'); x = sdpvar(2, 1); xp = sdpvar(2, 1);
F = [ xp == A*x ];
opt = optimizer(F, [], [], {x, A}, xp);
opt{{[1; 1], [1 1; 0 1]}}
```
```
Error using sfminbx (line 61)
Equal upper and lower bounds not permitted in trust-region-reflective algorithm. Use
either interior-point or SQP algorithms instead.

Error in fmincon (line 884)
      [X,FVAL,LAMBDA,EXITFLAG,OUTPUT,GRAD,HESSIAN] = ...

Error in callfmincon (line 58)
[xout,fmin,flag,output,lambda] =
fmincon('fmincon_fun',model.x0,model.A,model.b,model.Aeq,model.beq,model.lb,model.ub,callback_con,model.options.fmincon,model);

Error in optimizer/subsref (line 133)
                eval(['output = ' self.model.solver.call '(self.model);']);
```

**Comment by johanlofberg** [comment]
Isn't this simply a consequence of Mathworks bad consistency among version in what the different solver algorithms support and don't support. If so, it is no-fix. The user simply has to select a solver in fmincon which actually is capable of solving the problem, depending on the version of fmincon being used

**Comment by kvasnica** [comment]
Btw, why is fmincon chosen in the first place? Shouldn't this be solved by an LP solver by substituting `A` and `x`?

**Comment by johanlofberg** [comment]
Since this problem is linear for fixed parameters, this should be communicated to yalmip by explicitly selecting a lp/qp solver, to avoid a nonlinear solver being used. YALMIP sees bilinear expression, thus selects nonlinear solver.

**Comment by johanlofberg** [comment]
It's a future improvement to actually detect this and classify as linear problem, but it will not be done in the near future

**Comment by kvasnica** [comment]
My bad, I forgot about this. Consider this issue to be closed.
