### ISSUE TITLE
Speed of subsref access with a single index

### ISSUE THREAD

**Issue by jdbancal** [johanlofberg/YALMIP#348]
Access to part of a large sdpvar matrix seems to be unnecessarily slow...
Namely, accessing 864 elements from a 864x864 matrix with 160k variables as `matrix(i)` takes about 25 seconds, but if I replace lines 180 to 183 of subsref by the single command
    `Z = X.basis(ind1,:);`
then it comes down to 5 seconds, with apparently the same result. This time is comparable to what I observe when calling `matrix(i,1)`.

Is there any reason why these three lines should perform a double transposition? Is the line above safe?

**Comment by johanlofberg** [comment]
Hmm, good catch. Looks like some silly copy/paste laziness, but maybe I've coded around some utterly bizarre bug or performance issue on some version/architecture.
