### ISSUE TITLE
Subsasgn speed with variable overlap

### ISSUE THREAD

**Issue by jdbancal** [johanlofberg/YALMIP#349]
I'm impressed by how changing one element in a big sdpvar matrix is usually fast, even for very big and complicated matrices :-) For instance, I observed that changing one element of a 864x864 matrix with 160k variables with `sdpMatrix(1) = sdpvar(1)` takes only about 0.17 seconds.

It seems, however, that if the new value of the element to be changed contains an sdpvar which is already used in the matrix, then the software does something totally different... For instance, for the same matrix, doing `tmp = sdpMatrix(2)` followed by `sdpMatrix(1) = tmp` requires around 2 minutes and 40 seconds to complete the replacement (>1000x longer).

This long time seems to be due to an iteration that happens on line 198 of [subsasgn.m](https://github.com/johanlofberg/YALMIP/blob/develop/%40sdpvar/subsasgn.m). By changing 195 to 198 of this file by the following ones
```
                % Let's identify the indices at which we need to intervene
                case1 = find(in_yin_z==1);
                checkI = union(find(in_yin_z >= 2), setdiff(case1,case1+1));
                for i = checkI
                    switch in_yin_z(i)
                        case 1
                            % We look for the end of the block of ones
                            % starting at i
                            iend = i + find([in_yin_z(i+1:end) 0] ~= 1, 1, 'first')-1;
                            basis(:,i+1:iend+1) = z.basis(:,z_ind:z_ind+(iend-i));z_ind = z_ind+(iend-i)+1;
```
I obtained the same result in ~ 0.17 seconds.

Is this a safe modification?

**Comment by johanlofberg** [comment]
That probably requires some in-depth testing

**Comment by johanlofberg** [comment]
...highly appreciated though!

**Comment by jdbancal** [comment]
Actually, I noticed that the vector in_yin_z can sometimes be a horizontal vector, and other times a vertical vector... I'm not too sure why... But this means that a slight modification to the above code is necessary. Namely : 
```
                    % Let's identify the indices at which we need to intervene
                    case1 = find(in_yin_z==1);
                    checkI = union(find(in_yin_z >= 2), setdiff(case1,case1+1));
                    if size(checkI,1) > size(checkI,2)
                        % Sometimes the in_yin_z vector is vertical (not
                        % always though), so we make sure that checkI, on
                        % which we'll iterate, is horizontal.
                        checkI = checkI';
                    end
                    for i = checkI
                        switch in_yin_z(i)
                            case 1
                                % We look for the end of the block of ones
                                % starting at i
                                iend = i + find([in_yin_z(i+1:end) 0] ~= 1, 1, 'first')-1;
                                basis(:,i+1:iend+1) = z.basis(:,z_ind:z_ind+(iend-i));z_ind = z_ind+(iend-i)+1;
```

If one wants to go one step further, it's quite clear that one could treat all the cases 1 as one block outside of the for loop (like what is done just a few lines above in the code). I suspect that case 2 and 3 could also be treated by block, so that the for loop can be taken away altogether. However, I'm not too familiar with what is going on in these other cases, so I'm not too sure how to do that.

Please let me know if you have the chance to run some tests along these lines, I bet you can guess that gaining a factor 1000 in speed would be of interest to some of us ;-)
